title: "Genome annotation workshop"
baseurl: /workshop-genome_annotation

# where things are
layouts_dir: ./workshop-common/layouts
includes_dir: ./workshop-common/includes
sass:
  sass_dir: ./workshop-common/sass

plugins:
  - jemoji

defaults:
  - values:
      logosnav: true

menu:
  - title: Overview
    url: index
  - title: Location
    url: location
  - title: Uppmax&nbsp;login
    url: uppmax_login
  - title: Cheat&nbsp;sheets
    url: files/cheat_sheet/cheat_sheets
  - title: Schedule
    url: schedule
